/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./src/components/base/BaseCard.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BootstrapTest: typeof import('./src/components/bootstrapTest.vue')['default']
    CartList: typeof import('./src/components/Function-ProductList/CartList.vue')['default']
    CheckoutModal: typeof import('./src/components/Function-ProductList/CheckoutModal.vue')['default']
    Count: typeof import('./src/components/Count.vue')['default']
    IBiCart: typeof import('~icons/bi/cart')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    'ILucide:badgeX': typeof import('~icons/lucide/badge-x')['default']
    'ISvgSpinners:12DotsScaleRotate': typeof import('~icons/svg-spinners/12-dots-scale-rotate')['default']
    Login: typeof import('./src/components/backend/Login.vue')['default']
    LoveTalk: typeof import('./src/components/LoveTalk.vue')['default']
    Navbar: typeof import('./src/components/backend/Navbar.vue')['default']
    Person: typeof import('./src/components/Person.vue')['default']
    ProductCard: typeof import('./src/components/Function-ProductList/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingCart: typeof import('./src/components/shopping-cart.vue')['default']
    VBind: typeof import('./src/components/v-bind.vue')['default']
    Watch: typeof import('./src/components/watch.vue')['default']
  }
}
